[package]
name = "lanshare-client"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
lanshare-core = { workspace = true }
lanshare-net = { workspace = true }
tokio = { workspace = true }
rpassword = { workspace = true }
if-addrs = { workspace = true }
rayon = "1"
minifb = "0.28"
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_Media_MediaFoundation",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Ole",
    "Win32_System_Variant",
] }